export const ROLES = {
  ADMIN: 'TOUR MANAGER',
  MANAGER: 'TOUR MANAGER',
  TOUR_MANAGER: 'TOUR MANAGER',
  TEC_JEFE: 'TÉCNICO',
  JEFE_CAT_APV: 'TÉCNICO',
  TECH: 'TÉCNICO',
  TRASLADO: 'TÉCNICO',
  APV: 'TÉCNICO',
  ARTISTA: 'ARTISTA'
};

export const ESQUEMAS_MASTER_SECRET = 'Tk9fTWVfSGFja2VlczIwMjYhQCM=';
